name: Run HoundDog.ai Scan

on:
  push:
    branches: [main]
  schedule:
    # Every day at 9:00 AM PST (17:00 UTC; 10:00 AM during daylight saving time).
    - cron: "0 17 * * *"
  workflow_dispatch:
    inputs:
      debug:
        description: Enable debug logging
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  scan:
    name: Run HoundDog.ai Scan
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    container:
      image: hounddogai/hounddog:staging
      options: --pull=always
    env:
      HOUNDDOG_ENV: staging
      HOUNDDOG_API_KEY: ${{ secrets.HOUNDDOG_API_KEY_STAGING }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Run HoundDog.ai Scan
        run: hounddog scan ${{ inputs.debug && '--debug' || '' }}
